const DropDownStyle = {
  valueContainer: (base) => ({ ...base, maxWidth: "200px" }),
  placeholder: () => ({
    color: "#999",
    marginLeft: "2px",
    marginRight: "2px",
    position: "absolute",
    top: "50%",
    webkitTransform: "translateY(-50%)",
    msTransform: "translateY(-50%)",
    transform: "translateY(-50%)",
    boxSizing: "border-box",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: "calc(100% - 10px)",
    overflow: "hidden",
  }),
  indicatorSeparator: () => ({
    WebkitAlignSelf: "stretch",
    msFlexItemAlign: "stretch",
    alignSelf: "stretch",
    backgroundColor: "hsl(0,0%,80%)",
    marginBottom: 8,
    marginTop: 8,
    width: 1,
    boxSizing: "border-box",
  }),

  indicatorContainer: () => ({
    color: "rgb(102, 102, 102)",
    display: "flex",
    padding: 8,
    transition: "color 150ms ease 0s",
    boxSizing: "border-box",
  }),
  menu: () => ({
    top: "100%",
    backgroundColor: "rgb(255, 255, 255)",
    borderRadius: 4,
    boxShadow:
      "rgb(0 0 0 / 10%) 0px 0px 0px 1px, rgb(0 0 0 / 10%) 0px 4px 11px",
    marginBottom: 8,
    marginTop: 8,
    position: "absolute",
    width: "100%",
    zIndex: 1,
    boxSizing: "border-box",
  }),
  menuList: () => ({
    maxHeight: 300,
    overflowY: "auto",
    paddingBottom: 4,
    paddingTop: 4,
    position: "relative",
    boxSizing: "border-box",
    backgroundColor: "rgb(60, 60, 60)",
  }),
  container: () => ({
    position: "relative",
    boxSizing: "border-box",
    maxWidth: "100%",
    cursor: "initial",
  }),
  option: (provided, state) => ({
    backgroundColor: "transparent",
    color: "rgb(238, 238, 238)",
    cursor: "default",
    display: "block",
    fontSize: "inherit",
    padding: "8px 12px",
    width: "100%",
    userSelect: "none",
    WebkitTapHighlightColor: "rgba(0, 0, 0, 0)",
    boxSizing: "border-box",
  }),
  selected: () => ({
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    color: "rgb(238, 238, 238)",
    cursor: "default",
    display: "block",
    fontSize: "inherit",
    padding: "8px 12px",
    width: "100%",
    userSelect: "none",
    WebkitTapHighlightColor: "rgba(0, 0, 0, 0)",
    boxSizing: "border-box",
  }),
  control: () => ({
    WebkitAlignItems: "center",
    WebkitBoxAlign: "center",
    msFlexAlign: "center",
    alignItems: "center",
    backgroundColor: "#3c3c3c",
    borderColor: "#080808",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "none",
    cursor: "default",
    display: "flex",
    WebkitFlexWrap: "wrap",
    msFlexWrap: "wrap",
    flexWrap: "wrap",
    WebkitBoxPack: "justify",
    WebkitJustifyContent: "space-between",
    msFlexPack: "justify",
    justifyContent: "space-between",
    outline: "0 !important",
    position: "relative",
    WebkitTransition: "all 100ms",
    transition: "all 100ms",
    boxSizing: "border-box",
    height: 34,
    pointerEvents: "all",
  }),
  multiValue: () => ({
    backgroundColor: "",
  }),
  multiValueLabel: (base) => ({
    ...base,
    color: "white",
    whiteSpace: "nowrap",
    overflow: "hidden",
    maxWidth: "100%",
    textOverflow: "ellipsis",
    verticalAlign: "initial",
  }),
};
export default DropDownStyle;
